/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.ronghai.sa.view.panel;

import me.ronghai.sa.view.delegate.JTableBindingDelegate;
import org.jdesktop.beansbinding.AutoBinding;

/**
 *
 * @author L5M
 */
public class BasicCURDPanel extends javax.swing.JPanel {

    /**
     * Creates new form AbstractCURDPanel
     */
    public BasicCURDPanel() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataPanel = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        newButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        dataTable.setColumnSelectionAllowed(true);
        dataTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dataTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        dataPanel.setViewportView(dataTable);
        dataTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        newButton.setText("添加");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        editButton.setText("修改");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("删除");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteButton, editButton, newButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deleteButton, editButton, newButton});

    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Performed");
    }//GEN-LAST:event_newButtonActionPerformed

    private void dataTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dataTableAncestorAdded
        // TODO add your handling code here:
        System.out.println("Added");
    }//GEN-LAST:event_dataTableAncestorAdded

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Edit...");
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane dataPanel;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton newButton;
    // End of variables declaration//GEN-END:variables
    private JTableBindingDelegate<?> tableBindingDelegate;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    public JTableBindingDelegate<?> getTableBindingDelegate() {
        return tableBindingDelegate;
    }
    
    private org.jdesktop.swingbinding.JTableBinding getJTableBinding(JTableBindingDelegate<?> tableBindingDelegate){
        return tableBindingDelegate == null ? null : tableBindingDelegate.getJTableBinding(AutoBinding.UpdateStrategy.READ_WRITE, dataTable, "dataTableBinding");
    }
    
    private org.jdesktop.swingbinding.JTableBinding binding = null;
    public void setTableBindingDelegate(JTableBindingDelegate<?> tableBindingDelegate) {
        org.jdesktop.swingbinding.JTableBinding _binding = this.getJTableBinding(tableBindingDelegate);
        if (tableBindingDelegate == this.tableBindingDelegate) {
            if (this.binding == _binding) {
                this.binding.bind();
                this.binding.refresh();
                return;
            }
        }
        if (this.binding != null) {
            this.bindingGroup.removeBinding(binding);
            if (binding.isBound()) {
                binding.unbind();
            }
        }
        this.binding = _binding;
        this.tableBindingDelegate = tableBindingDelegate;
        if (binding != null) {
            this.bindingGroup.addBinding(binding);
            binding.bind();
        }
        this.bindingGroup.bind();
    }
}
