/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package me.ronghai.sa.view.panel;

import javax.persistence.EntityManager;
import me.ronghai.sa.model.Client;

/**
 *
 * @author L5M
 */
public class ClientManagementPanel extends AbstractPanel{

    /**
     * Creates new form ClientManagementPanel
     */
    public ClientManagementPanel() {
        initComponents();
        EntityManager entityManager = java.beans.Beans.isDesignTime() ? null : 
                javax.persistence.Persistence.createEntityManagerFactory("SaleAssistantPU").createEntityManager();
        System.out.println(entityManager.find(Client.class , 1L ).getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
